const FONTS = {
  ALBERT: 'Albert, sans-serif',
  BARLOW: 'Barlow, sans-serif',
};

const COLOR = {
  PRIMARY: '#6C757D',
  SECONDARY: '#E1F4CB',
  TERTIARY: '#FBBC05',
  FOURTHARY: '#EA4335',
  ACCENT: '#3F51B5',

  BACKGROUND: '#F5F5F5',
  TEXT: '#9A55FF', 
  ERROR: '#FF0000',
  WARNING: '#FFA726',
  SUCCESS: '#4CAF50',
  CUSTOM:"#62912C",
  SECONDRYRED:'#ED4D5C',
  SECONDRYCARDCOLOR:'#FFE3E6',
  SECONDRYBLUE:'#41A5FF',
  SECONDRYBLUECOLOR:'#DBEEFF'
  
};

// Use named exports
export { FONTS, COLOR }; 
